=== aihiao999/Xml/011_XSD-schema元素/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lywgames.com"
	elementFormDefault="qualified">
	<element name="students">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element name="student">
					<complexType>
						<sequence>
							<element name="name" type="string"></element>
							<element name="age" type="int"></element>
							<element name="sex" type="string"></element>
						</sequence>
						<attribute name="id" type="string" default=""/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== aihiao999/Xml/011_XSD-schema元素/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<students xmlns="http://www.lywgames.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lywgames.com students.xsd">
	<student id="10086">
		<name>刘邦</name>
		<age>18</age>
		<sex>男</sex>
	</student>
	<student id="10087">
		<name>吕雉</name>
		<age>16</age>
		<sex>女</sex>
	</student>
</students>
